# backend/api/risk.py
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from pydantic import BaseModel
from backend.services.ml_service import predict_flood_risk
from backend.database import crud, connection

router = APIRouter()

class TelemetryData(BaseModel):
    sensor_id: str
    rainfall_mm: float
    soil_moisture_percentage: float
    river_level_meters: float

@router.post("/evaluate")
def evaluate_sensor_telemetry(data: TelemetryData, db: Session = Depends(connection.get_db)):
    # 1. Prediction score nikalna
    assessment = predict_flood_risk(data.rainfall_mm, data.soil_moisture_percentage, data.river_level_meters)
    
    # 2. Step 7 Implementation: Auto-trigger system agar risk 'High' ho
    if assessment["risk_level"] == "High":
        crud.create_alert(
            db=db,
            sensor_id=data.sensor_id,
            risk_level="High",
            description=f"Auto-generated by ML Engine: {assessment['decision']}"
        )
        assessment["alert_triggered"] = True
    else:
        assessment["alert_triggered"] = False
    
    return assessment